version: "2"

linters:
  default: standard
  enable:
    - errcheck
    - gocritic
    - ineffassign
    - misspell
    - unconvert
  exclusions:
    generated: strict
    rules:
      - path: ^control/bpf_stub\.go$
        linters:
          - unused
      - path: ^control/netkit_linux\.go$
        linters:
          - unused
      - path: ^control/netkit_netlink\.go$
        linters:
          - unused

formatters:
  enable:
    - gofmt
