name: Enhancement
description: suggest an enhancement to the dae project
title: '[Enhancement] <title>'
labels: [topic/enhancement]
body:
  - type: textarea
    attributes:
      label: Improvement Suggestion
      description: What would you like us to improve.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Potential Benefits
      description: Why is this needed.
    validations:
      required: false
