name: Proposal
description: new feature proposal (developer only)
title: '[Proposal] <title>'
labels: ['topic/proposal']
body:
  - type: textarea
    attributes:
      label: Proposal
      description: What new feature you would like to integrate into the dae project.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Use Cases
      description: What use cases the proposed new feature is categorized to.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Potential Benefits
      description: Why is this needed.
    validations:
      required: true

  - type: textarea
    attributes:
      label: Scope
      description: What needs to be done.
    validations:
      required: false

  - type: textarea
    attributes:
      label: Reference
      description: Useful links
    validations:
      required: false

  - type: textarea
    attributes:
      label: Implementation
      description: PR links to this issue.
    validations:
      required: false

