// Code generated by go run ../../scripts/gen_ebpf_sync.go; DO NOT EDIT.

package consts

type MatchType uint8

const (
	MatchType_DomainSet MatchType = iota
	MatchType_IpSet
	MatchType_SourceIpSet
	MatchType_Port
	MatchType_SourcePort
	MatchType_L4Proto
	MatchType_IpVersion
	MatchType_Mac
	MatchType_ProcessName
	MatchType_Dscp
	MatchType_Fallback
	MatchType_MustRules
	MatchType_Upstream
	MatchType_QType
)

type OutboundIndex uint8

const (
	OutboundDirect              OutboundIndex = 0x0
	OutboundBlock               OutboundIndex = 0x1
	OutboundMustRules           OutboundIndex = 0xFC
	OutboundControlPlaneRouting OutboundIndex = 0xFD
	OutboundLogicalOr           OutboundIndex = 0xFE
	OutboundLogicalAnd          OutboundIndex = 0xFF
	OutboundLogicalMask         OutboundIndex = 0xFE
	OutboundUserDefinedMin      OutboundIndex = OutboundBlock + 1
	OutboundUserDefinedMax                    = OutboundMustRules - 1
)

type L4ProtoType uint8

const (
	L4ProtoType_TCP     L4ProtoType = 1
	L4ProtoType_UDP     L4ProtoType = 2
	L4ProtoType_X       L4ProtoType = 3
	L4ProtoType_TCP_UDP L4ProtoType = L4ProtoType_X
)

type IpVersionType uint8

const (
	IpVersion_4 IpVersionType = 1
	IpVersion_6 IpVersionType = 2
	IpVersion_X IpVersionType = 3
)
