// SPDX-License-Identifier: AGPL-3.0-only
// Copyright (c) 2022-2025, daeuniverse Organization <dae@v2raya.org>

package main

import (
	"bytes"
	"encoding/json"
	"fmt"
	"go/format"
	"os"
	"path/filepath"
	"runtime"
	"strings"
	"unicode"
)

type namedValue struct {
	Name  string `json:"name"`
	Value uint32 `json:"value"`
}

type syncSpec struct {
	MatchTypes []string     `json:"match_types"`
	L4Proto    []namedValue `json:"l4_proto"`
	IpVersion  []namedValue `json:"ip_version"`
	Outbound   []namedValue `json:"outbound"`
}

func main() {
	root, err := findRepoRoot()
	must(err)

	specPath := filepath.Join(root, "common", "consts", "ebpf_sync_spec.json")
	raw, err := os.ReadFile(specPath)
	must(err)

	var spec syncSpec
	must(json.Unmarshal(raw, &spec))
	must(validateSpec(spec))

	goOut := filepath.Join(root, "common", "consts", "ebpf_generated.go")
	hOut := filepath.Join(root, "control", "kern", "ebpf_sync_defs.h")

	must(writeGo(goOut, spec))
	must(writeHeader(hOut, spec))
}

func findRepoRoot() (string, error) {
	if root, err := findRepoRootFromWD(); err == nil {
		return root, nil
	}
	_, file, _, ok := runtime.Caller(0)
	if !ok {
		return "", fmt.Errorf("runtime.Caller failed")
	}
	dir := filepath.Dir(file)
	return findRepoRootByWalking(dir)
}

func findRepoRootFromWD() (string, error) {
	wd, err := os.Getwd()
	if err != nil {
		return "", err
	}
	return findRepoRootByWalking(wd)
}

func findRepoRootByWalking(start string) (string, error) {
	dir := start
	for {
		if _, err := os.Stat(filepath.Join(dir, "go.mod")); err == nil {
			return dir, nil
		}
		parent := filepath.Dir(dir)
		if parent == dir {
			return "", fmt.Errorf("go.mod not found from %s", start)
		}
		dir = parent
	}
}

func validateSpec(spec syncSpec) error {
	if len(spec.MatchTypes) == 0 {
		return fmt.Errorf("match_types is empty")
	}
	if len(spec.L4Proto) == 0 {
		return fmt.Errorf("l4_proto is empty")
	}
	if len(spec.IpVersion) == 0 {
		return fmt.Errorf("ip_version is empty")
	}
	if len(spec.Outbound) == 0 {
		return fmt.Errorf("outbound is empty")
	}
	return nil
}

func writeGo(path string, spec syncSpec) error {
	var b bytes.Buffer
	b.WriteString("// Code generated by go run ../../scripts/gen_ebpf_sync.go; DO NOT EDIT.\n")
	b.WriteString("\n")
	b.WriteString("package consts\n\n")

	b.WriteString("type MatchType uint8\n\n")
	b.WriteString("const (\n")
	for i, name := range spec.MatchTypes {
		if i == 0 {
			b.WriteString(fmt.Sprintf("\tMatchType_%s MatchType = iota\n", name))
		} else {
			b.WriteString(fmt.Sprintf("\tMatchType_%s\n", name))
		}
	}
	b.WriteString(")\n\n")

	b.WriteString("type OutboundIndex uint8\n\n")
	b.WriteString("const (\n")
	for _, nv := range spec.Outbound {
		b.WriteString(fmt.Sprintf("\t%s OutboundIndex = 0x%X\n", goOutboundName(nv.Name), nv.Value))
	}
	b.WriteString("\tOutboundUserDefinedMin OutboundIndex = OutboundBlock + 1\n")
	b.WriteString("\tOutboundUserDefinedMax               = OutboundMustRules - 1\n")
	b.WriteString(")\n\n")

	b.WriteString("type L4ProtoType uint8\n\n")
	b.WriteString("const (\n")
	for _, nv := range spec.L4Proto {
		b.WriteString(fmt.Sprintf("\t%s L4ProtoType = %d\n", goL4Name(nv.Name), nv.Value))
	}
	b.WriteString("\tL4ProtoType_TCP_UDP L4ProtoType = L4ProtoType_X\n")
	b.WriteString(")\n\n")

	b.WriteString("type IpVersionType uint8\n\n")
	b.WriteString("const (\n")
	for _, nv := range spec.IpVersion {
		b.WriteString(fmt.Sprintf("\t%s IpVersionType = %d\n", goIPVersionName(nv.Name), nv.Value))
	}
	b.WriteString(")\n")

	src, err := format.Source(b.Bytes())
	if err != nil {
		return fmt.Errorf("format go output: %w", err)
	}
	return os.WriteFile(path, src, 0644)
}

func writeHeader(path string, spec syncSpec) error {
	var b bytes.Buffer
	b.WriteString("/* Code generated by go run ../../scripts/gen_ebpf_sync.go; DO NOT EDIT. */\n")
	b.WriteString("\n")
	b.WriteString("#ifndef DAE_EBPF_SYNC_DEFS_H\n")
	b.WriteString("#define DAE_EBPF_SYNC_DEFS_H\n\n")

	for _, nv := range spec.Outbound {
		b.WriteString(fmt.Sprintf("#define OUTBOUND_%s 0x%X\n", nv.Name, nv.Value))
	}
	b.WriteString("\n")

	b.WriteString("enum __attribute__((packed)) MatchType {\n")
	for i, name := range spec.MatchTypes {
		b.WriteString(fmt.Sprintf("\tMatchType_%s = %d,\n", name, i))
	}
	b.WriteString("};\n\n")

	b.WriteString("enum L4ProtoType {\n")
	for _, nv := range spec.L4Proto {
		b.WriteString(fmt.Sprintf("\tL4ProtoType_%s = %d,\n", nv.Name, nv.Value))
	}
	b.WriteString("};\n\n")

	b.WriteString("enum IpVersionType {\n")
	for _, nv := range spec.IpVersion {
		b.WriteString(fmt.Sprintf("\tIpVersionType_%s = %d,\n", nv.Name, nv.Value))
	}
	b.WriteString("};\n\n")

	b.WriteString("#endif\n")
	return os.WriteFile(path, b.Bytes(), 0644)
}

func goOutboundName(cName string) string {
	switch cName {
	case "DIRECT":
		return "OutboundDirect"
	case "BLOCK":
		return "OutboundBlock"
	case "MUST_RULES":
		return "OutboundMustRules"
	case "CONTROL_PLANE_ROUTING":
		return "OutboundControlPlaneRouting"
	case "LOGICAL_OR":
		return "OutboundLogicalOr"
	case "LOGICAL_AND":
		return "OutboundLogicalAnd"
	case "LOGICAL_MASK":
		return "OutboundLogicalMask"
	default:
		return "Outbound" + toCamel(strings.ToLower(cName))
	}
}

func goL4Name(name string) string {
	switch name {
	case "TCP":
		return "L4ProtoType_TCP"
	case "UDP":
		return "L4ProtoType_UDP"
	case "X":
		return "L4ProtoType_X"
	default:
		return "L4ProtoType_" + name
	}
}

func goIPVersionName(name string) string {
	switch name {
	case "4":
		return "IpVersion_4"
	case "6":
		return "IpVersion_6"
	case "X":
		return "IpVersion_X"
	default:
		return "IpVersion_" + name
	}
}

func must(err error) {
	if err != nil {
		panic(err)
	}
}

func toCamel(s string) string {
	parts := strings.Split(s, "_")
	var b strings.Builder
	for _, p := range parts {
		if p == "" {
			continue
		}
		runes := []rune(p)
		runes[0] = unicode.ToUpper(runes[0])
		b.WriteString(string(runes))
	}
	return b.String()
}
