//go:build !dae_stub_ebpf

/*
 * SPDX-License-Identifier: AGPL-3.0-only
 * Copyright (c) 2022-2026, daeuniverse Organization <dae@v2raya.org>
 */

package control

import (
	"bufio"
	"errors"
	"fmt"
	"net/netip"
	"os"
	"path/filepath"
	"reflect"
	"runtime"
	"strings"
	"sync"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/asm"
	"github.com/cilium/ebpf/features"
	"github.com/daeuniverse/dae/common"
	"github.com/daeuniverse/dae/common/consts"
	daerrors "github.com/daeuniverse/dae/common/errors"
	internal "github.com/daeuniverse/dae/pkg/ebpf_internal"
	"github.com/sirupsen/logrus"
)

// ============================================================================
// BPF Type Synchronization
// ============================================================================
//
// Most BPF types are auto-generated by bpf2go in bpf_bpfel.go:
// - bpfTuplesKey (struct tuples_key) - auto-generated, five-tuple key
// - bpfDomainRouting (struct domain_routing)
// - bpfPortRange (struct port_range) - auto-generated via -type flag
// - bpfMatchSet, bpfPidPname, bpfRedirectEntry, etc.
//
// However, some types cannot be auto-generated and are defined here:
// - bpfRoutingResult (struct routing_result) - userspace routing metadata
// - _bpfLpmKey (struct lpm_key) - contains bpf_lpm_trie_key (kernel BPF type)
//
// Note: _bpfTuples was removed as it was unused in the codebase.
// Note: BPF LPM Trie requires the exact bpf_lpm_trie_key structure for
// kernel type recognition. Flattening breaks BPF map operations.
//
// To verify synchronization:
// 1. Check struct size matches (use unsafe.Sizeof in Go, sizeof in C)
// 2. Check field offsets match
// 3. Run BPF tests: go test -tags="linux dae_bpf_tests" ./control/kern/tests/...
// ============================================================================

type bpfRoutingResult struct {
	Mark               uint32
	Must               uint8
	Mac                [6]uint8
	Outbound           uint8
	Pname              [16]uint8
	Pid                uint32
	Dscp               uint8
	RoutingEpochSlot   uint8
	DatapathGeneration uint16
}

type _bpfLpmKey struct {
	PrefixLen uint32
	Data      [4]uint32
}

// bpfPortRange is auto-generated by bpf2go. Its host-ABI codec lives in
// bpf_host_abi.go so real and stub builds use the same byte order.

func (o *bpfObjects) newLpmMap(keys []_bpfLpmKey, values []uint32) (m *ebpf.Map, err error) {
	m, err = ebpf.NewMap(&ebpf.MapSpec{
		Type:       ebpf.LPMTrie,
		Flags:      o.UnusedLpmType.Flags(),
		MaxEntries: o.UnusedLpmType.MaxEntries(),
		KeySize:    o.UnusedLpmType.KeySize(),
		ValueSize:  o.UnusedLpmType.ValueSize(),
	})
	if err != nil {
		return nil, err
	}
	if _, err = BpfMapBatchUpdate(m, keys, values, &ebpf.BatchOptions{
		ElemFlags: uint64(ebpf.UpdateAny),
	}); err != nil {
		_ = m.Close()
		return nil, err
	}
	return m, nil
}

func cidrToBpfLpmKey(prefix netip.Prefix) _bpfLpmKey {
	bits := prefix.Bits()
	addr := prefix.Addr()
	if addr.Is4In6() && bits <= 32 {
		// An IPv4-mapped prefix written with an IPv4 bit count
		// (::ffff:1.2.3.0/24, plus the 16-byte encoding used by geoip .dat
		// data). The datapath always encodes IPv4 in the mapped form
		// (::ffff:a.b.c.d with a 96+bits prefix length), so storing the
		// first `bits` bits of the mapped address - which are all zero -
		// would match every IPv4 address. Unmap first and let the Is4
		// branch below re-add the 96-bit mapping offset. A bit count above
		// 32 already is the mapped spelling of an IPv4 prefix and needs no
		// rewrite. Keep this rule identical to pkg/trie.Prefix2bin128.
		addr = addr.Unmap()
	}
	if addr.Is4() {
		bits += 96
	}
	ip := addr.As16()
	return _bpfLpmKey{
		PrefixLen: uint32(bits),
		Data:      common.Ipv6ByteSliceToUint32Array(ip[:]),
	}
}

var (
	CheckBatchUpdateFeatureOnce sync.Once
	SimulateBatchUpdate         bool
	SimulateBatchUpdateLpmTrie  bool

	CheckBatchDeleteFeatureOnce sync.Once
	SimulateBatchDelete         bool
)

func initBatchDeleteFeatureFlags() {
	CheckBatchDeleteFeatureOnce.Do(func() {
		version, e := internal.KernelVersion()
		if e != nil {
			SimulateBatchDelete = true
			return
		}
		// BatchDelete requires kernel 5.6+ for BPF_MAP_TYPE_BATCH operations.
		if version.Less(consts.UserspaceBatchUpdateFeatureVersion) {
			SimulateBatchDelete = true
		}
	})
}

func BpfMapBatchUpdate(m *ebpf.Map, keys any, values any, opts *ebpf.BatchOptions) (n int, err error) {
	CheckBatchUpdateFeatureOnce.Do(func() {
		version, e := internal.KernelVersion()
		if e != nil {
			SimulateBatchUpdate = true
			SimulateBatchUpdateLpmTrie = true
			return
		}
		if version.Less(consts.UserspaceBatchUpdateFeatureVersion) {
			SimulateBatchUpdate = true
		}
		if version.Less(consts.UserspaceBatchUpdateLpmTrieFeatureVersion) {
			SimulateBatchUpdateLpmTrie = true
		}
	})

	simulate := SimulateBatchUpdate
	if m.Type() == ebpf.LPMTrie {
		simulate = SimulateBatchUpdateLpmTrie
	}

	if !simulate {
		// Genuine BpfMapBatchUpdate
		return m.BatchUpdate(keys, values, opts)
	}

	// Simulate
	vKeys := reflect.ValueOf(keys)
	if vKeys.Kind() != reflect.Slice {
		return 0, fmt.Errorf("keys must be slice")
	}
	vVals := reflect.ValueOf(values)
	if vVals.Kind() != reflect.Slice {
		return 0, fmt.Errorf("values must be slice")
	}
	length := vKeys.Len()
	if vVals.Len() != length {
		return 0, fmt.Errorf("keys and values must have same length")
	}

	for i := range length {
		vKey := vKeys.Index(i)
		vVal := vVals.Index(i)
		if err = m.Update(vKey.Interface(), vVal.Interface(), ebpf.MapUpdateFlags(opts.ElemFlags)); err != nil {
			return i, fmt.Errorf("batch update map %s at index %d: %w", m.String(), i, err)
		}
	}
	return vKeys.Len(), nil
}

// BpfMapBatchDelete deletes keys, ignores ErrKeyNotExist, and returns the
// number of entries actually deleted. The kernel stops a batch at the first
// missing key, so ENOENT must resume at the following key instead of being
// treated as success for the unprocessed suffix.
func BpfMapBatchDelete(m *ebpf.Map, keys any) (n int, err error) {
	initBatchDeleteFeatureFlags()

	vKeys := reflect.ValueOf(keys)
	if vKeys.Kind() != reflect.Slice {
		return 0, fmt.Errorf("keys must be slice")
	}

	if !SimulateBatchDelete {
		n, err = batchDeleteIgnoringMissing(vKeys, func(suffix any) (int, error) {
			return m.BatchDelete(suffix, &ebpf.BatchOptions{})
		})
		if err != nil {
			return n, fmt.Errorf("batch delete map %s: %w", m.String(), err)
		}
		return n, nil
	}

	deleted := 0
	for i := range vKeys.Len() {
		vKey := vKeys.Index(i)
		err = m.Delete(vKey.Interface())
		switch {
		case err == nil:
			deleted++
		case errors.Is(err, ebpf.ErrKeyNotExist):
			continue
		default:
			return deleted, fmt.Errorf("batch delete map %s at index %d: %w", m.String(), i, err)
		}
	}
	return deleted, nil
}

func batchDeleteIgnoringMissing(vKeys reflect.Value, deleteBatch func(keys any) (int, error)) (deleted int, err error) {
	length := vKeys.Len()
	for cursor := 0; cursor < length; {
		remaining := length - cursor
		n, batchErr := deleteBatch(vKeys.Slice(cursor, length).Interface())
		if n < 0 || n > remaining {
			return deleted, fmt.Errorf("invalid processed count %d for %d keys", n, remaining)
		}
		deleted += n
		cursor += n

		if batchErr == nil {
			if cursor != length {
				return deleted, fmt.Errorf("stopped without error after %d of %d keys", cursor, length)
			}
			return deleted, nil
		}
		if !errors.Is(batchErr, ebpf.ErrKeyNotExist) {
			return deleted, batchErr
		}

		// Count points at the missing key. Skip that key and retry the suffix.
		if cursor < length {
			cursor++
		}
	}
	return deleted, nil
}

var detectCgroupPathCached = sync.OnceValues(scanCgroupPath)

// detectCgroupPath returns the first-found mount point of type cgroup2,
// caching the result for the lifetime of the process to avoid repeatedly
// scanning /proc/mounts on reloads or multiple setups.
func detectCgroupPath() (string, error) {
	return detectCgroupPathCached()
}

func scanCgroupPath() (string, error) {
	f, err := os.Open("/proc/mounts")
	if err != nil {
		return "", err
	}
	defer func() { _ = f.Close() }()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		// example fields: cgroup2 /sys/fs/cgroup/unified cgroup2 rw,nosuid,nodev,noexec,relatime 0 0
		fields := strings.Fields(scanner.Text())
		if len(fields) >= 3 && fields[2] == "cgroup2" {
			return fields[1], nil
		}
	}
	if err := scanner.Err(); err != nil {
		return "", fmt.Errorf("read /proc/mounts: %w", err)
	}

	return "", errors.New("cgroup2 not mounted")
}

type bpfIfParams struct {
	RxCksmOffload                  bool
	TxL4CksmIp4Offload             bool
	TxL4CksmIp6Offload             bool
	UseNonstandardOffloadAlgorithm bool
}

func (p bpfIfParams) CheckVersionRequirement(version *internal.Version) (err error) {
	if !p.TxL4CksmIp4Offload ||
		!p.TxL4CksmIp6Offload {
		// Need calc checksum on CPU. And need BPF_F_ADJ_ROOM_NO_CSUM_RESET.
		if version.Less(consts.ChecksumFeatureVersion) {
			return fmt.Errorf("your NIC does not support checksum offload and your kernel version %v does not support related BPF features; expect >=%v; upgrade your kernel and try again", version.String(),
				consts.ChecksumFeatureVersion.String())
		}
	}
	return nil
}

type loadBpfOptions struct {
	PinPath                    string
	BigEndianTproxyPort        uint32
	CollectionOptions          *ebpf.CollectionOptions
	ConnStateMapMaxEntries     uint32
	RedirectTrackMapMaxEntries uint32
	DatapathGeneration         uint16
}

const (
	defaultConnStateMapMaxEntries = 65536 * 4
	// defaultRedirectTrackMapMaxEntries mirrors MAX_REDIRECT_TRACK_NUM in
	// kern/tproxy.c and is cross-checked against the compiled map capacity by
	// tuneRedirectTrackMap. The C default is deliberately kept: raising it to
	// 262144 must be justified by measuring resident memory first (HASH
	// without preallocation only preallocates the bucket array, so the cost
	// is dominated by live entries: roughly 24 B value + 48 B key + element
	// overhead per entry), see the D4 report.
	defaultRedirectTrackMapMaxEntries = 65536
)

// The blocked-event rate-limit contract values (blockedEventRateKey,
// blockedEventRateWindowNs, expectedInjectedVariables, eventRateValue) live
// in event_rate_contract.go, which compiles under both the real-eBPF build
// and the dae_stub_ebpf test build so the parity tests can pin them against
// the kernel source.

// bpfDataplanePrograms mirrors the always-on datapath programs declared in the
// generated bpfPrograms, but WITHOUT the opt-in tcp_offload_* programs. It is the
// binding target for the first (mandatory) load pass so that a trimmed kernel
// that cannot load a specific offload program (e.g. fentry/skb_send_sock on
// OpenWrt) cannot take down the whole datapath at start. The offload programs
// are loaded in a separate, fault-tolerant pass (see loadOffloadBpfPrograms).
type bpfDataplanePrograms struct {
	TproxyDae0Ingress      *ebpf.Program `ebpf:"tproxy_dae0_ingress"`
	TproxyDae0peerIngress  *ebpf.Program `ebpf:"tproxy_dae0peer_ingress"`
	TproxyLanEgressL2      *ebpf.Program `ebpf:"tproxy_lan_egress_l2"`
	TproxyLanEgressL3      *ebpf.Program `ebpf:"tproxy_lan_egress_l3"`
	TproxyLanIngressL2     *ebpf.Program `ebpf:"tproxy_lan_ingress_l2"`
	TproxyLanIngressL3     *ebpf.Program `ebpf:"tproxy_lan_ingress_l3"`
	TproxyLanWanEgressL2   *ebpf.Program `ebpf:"tproxy_lan_wan_egress_l2"`
	TproxyLanWanEgressL3   *ebpf.Program `ebpf:"tproxy_lan_wan_egress_l3"`
	TproxyWanCgConnect4    *ebpf.Program `ebpf:"tproxy_wan_cg_connect4"`
	TproxyWanCgConnect6    *ebpf.Program `ebpf:"tproxy_wan_cg_connect6"`
	TproxyWanCgSendmsg4    *ebpf.Program `ebpf:"tproxy_wan_cg_sendmsg4"`
	TproxyWanCgSendmsg6    *ebpf.Program `ebpf:"tproxy_wan_cg_sendmsg6"`
	TproxyWanCgSockCreate  *ebpf.Program `ebpf:"tproxy_wan_cg_sock_create"`
	TproxyWanCgSockRelease *ebpf.Program `ebpf:"tproxy_wan_cg_sock_release"`
	TproxyWanEgressL2      *ebpf.Program `ebpf:"tproxy_wan_egress_l2"`
	TproxyWanEgressL3      *ebpf.Program `ebpf:"tproxy_wan_egress_l3"`
	TproxyWanIngressL2     *ebpf.Program `ebpf:"tproxy_wan_ingress_l2"`
	TproxyWanIngressL3     *ebpf.Program `ebpf:"tproxy_wan_ingress_l3"`
	TproxyWanLanIngressL2  *ebpf.Program `ebpf:"tproxy_wan_lan_ingress_l2"`
	TproxyWanLanIngressL3  *ebpf.Program `ebpf:"tproxy_wan_lan_ingress_l3"`
}

// bpfDataplaneMaps mirrors the always-on datapath maps declared in the generated
// bpfMaps, but WITHOUT the opt-in offload maps (fast_sock, tcp_offload_pause,
// tcp_offload_sent). Used as the binding target for the mandatory load pass.
type bpfDataplaneMaps struct {
	ActiveRoutingEpochMap    *ebpf.Map `ebpf:"active_routing_epoch_map"`
	AliveBlockRateMap        *ebpf.Map `ebpf:"alive_block_rate_map"`
	BpfStatsMap              *ebpf.Map `ebpf:"bpf_stats_map"`
	ConnStateMap             *ebpf.Map `ebpf:"conn_state_map"`
	ConntrackArgsMap         *ebpf.Map `ebpf:"conntrack_args_map"`
	CookiePidMap             *ebpf.Map `ebpf:"cookie_pid_map"`
	DaeIfindexMap            *ebpf.Map `ebpf:"dae_ifindex_map"`
	DomainRoutingMap         *ebpf.Map `ebpf:"domain_routing_map"`
	EventRingbuf             *ebpf.Map `ebpf:"event_ringbuf"`
	ListenSocketMap          *ebpf.Map `ebpf:"listen_socket_map"`
	LpmArrayMap              *ebpf.Map `ebpf:"lpm_array_map"`
	OutboundConnectivityMap  *ebpf.Map `ebpf:"outbound_connectivity_map"`
	ParseCtxScratchMap       *ebpf.Map `ebpf:"parse_ctx_scratch_map"`
	PktScratchMap            *ebpf.Map `ebpf:"pkt_scratch_map"`
	RedirectTrack            *ebpf.Map `ebpf:"redirect_track"`
	RouteCtxScratchMap       *ebpf.Map `ebpf:"route_ctx_scratch_map"`
	RoutingHandoffMap        *ebpf.Map `ebpf:"routing_handoff_map"`
	RoutingMap               *ebpf.Map `ebpf:"routing_map"`
	RoutingMetaMap           *ebpf.Map `ebpf:"routing_meta_map"`
	UnusedLpmType            *ebpf.Map `ebpf:"unused_lpm_type"`
	WanEgressRouteScratchMap *ebpf.Map `ebpf:"wan_egress_route_scratch_map"`
}

// bpfDataplane is the mandatory-load binding target. It intentionally lacks the
// opt-in tcp_offload_* programs and maps so the mandatory LoadAndAssign pass does
// not bind them; they are loaded in a separate fault-tolerant pass.
type bpfDataplane struct {
	bpfDataplanePrograms
	bpfDataplaneMaps
	bpfVariables
}

func loadBpfObjectsWithConstantsAndCustomizer(
	obj any,
	opts *ebpf.CollectionOptions,
	constants map[string]any,
	customize func(spec *ebpf.CollectionSpec) error,
) error {
	spec, err := loadBpf()
	if err != nil {
		return err
	}
	for name, value := range constants {
		v, ok := spec.Variables[name]
		if !ok || v == nil {
			return fmt.Errorf("inject eBPF constant %q: variable not found in collection spec; the kernel-side declaration was likely removed or renamed — keep the Go-side constants map in sync with kern/tproxy.c .rodata variables", name)
		}
		if err := v.Set(value); err != nil {
			return err
		}
	}
	// Completeness guard: every expected .rodata variable must actually be
	// injected above. A variable missing from the constants map would
	// otherwise silently fall back to its C-side initializer (e.g. the
	// clang fallback of EVENT_RATE), and a map geometry derived on the Go
	// side could diverge from the value the kernel actually runs with.
	for _, name := range expectedInjectedVariables {
		if _, ok := constants[name]; !ok {
			return fmt.Errorf("eBPF constant %q is expected to be injected but missing from the constants map", name)
		}
	}
	if customize != nil {
		if err := customize(spec); err != nil {
			return err
		}
	}
	return spec.LoadAndAssign(obj, opts)
}

func disablePinnedConnStateMaps(spec *ebpf.CollectionSpec) error {
	if spec == nil {
		return fmt.Errorf("nil collection spec")
	}
	m, ok := spec.Maps["conn_state_map"]
	if !ok || m == nil {
		return fmt.Errorf("missing map spec %q", "conn_state_map")
	}
	m.Pinning = ebpf.PinNone
	return nil
}

func tuneConnStateBpfMap(spec *ebpf.CollectionSpec, maxEntries uint32) error {
	if spec == nil {
		return fmt.Errorf("nil collection spec")
	}
	if maxEntries == 0 {
		maxEntries = defaultConnStateMapMaxEntries
	}
	connState, ok := spec.Maps["conn_state_map"]
	if !ok || connState == nil {
		return fmt.Errorf("missing map spec %q", "conn_state_map")
	}
	connState.MaxEntries = maxEntries
	return nil
}

// tuneRedirectTrackMap is the single owner of the redirect_track capacity.
// The map is declared in kern/tproxy.c with MAX_REDIRECT_TRACK_NUM, and
// userspace used to carry a second hard-coded copy of the same number for its
// usage warnings; the two could drift silently. Here the compiled capacity is
// cross-checked against the Go constant (defaultRedirectTrackMapMaxEntries,
// which mirrors the C macro) and any divergence fails the load instead of
// quietly resizing or mis-reporting. Growth past the C default is an explicit
// decision: HASH without preallocation only preallocates the bucket array, so
// raising it costs memory only as entries are actually used.
func tuneRedirectTrackMap(spec *ebpf.CollectionSpec, maxEntries uint32) error {
	if spec == nil {
		return fmt.Errorf("nil collection spec")
	}
	if maxEntries == 0 {
		maxEntries = defaultRedirectTrackMapMaxEntries
	}
	m, ok := spec.Maps["redirect_track"]
	if !ok || m == nil {
		return fmt.Errorf("missing map spec %q", "redirect_track")
	}
	if m.MaxEntries != maxEntries {
		return fmt.Errorf("redirect_track capacity %d diverges from the expected %d (MAX_REDIRECT_TRACK_NUM in kern/tproxy.c and defaultRedirectTrackMapMaxEntries in bpf_utils.go must agree)",
			m.MaxEntries, maxEntries)
	}
	m.MaxEntries = maxEntries
	return nil
}

func customizeBpfMapSpecs(spec *ebpf.CollectionSpec, connStateMapMaxEntries, redirectTrackMapMaxEntries uint32) error {
	if err := disablePinnedConnStateMaps(spec); err != nil {
		return err
	}
	if err := tuneConnStateBpfMap(spec, connStateMapMaxEntries); err != nil {
		return err
	}
	return tuneRedirectTrackMap(spec, redirectTrackMapMaxEntries)
}

// tuneEventRateMap derives the alive_block_rate_map capacity from the same
// userspace-owned reserved keys that get injected into the EVENT_RATE rodata
// variable, so the key domain and the ARRAY geometry share a single owner
// (the map definition on the C side can only reference a compile-time
// fallback constant). The derived invariant matches the C fallback exactly:
// capacity = highest reserved key + 1.
func tuneEventRateMap(spec *ebpf.CollectionSpec) error {
	if spec == nil {
		return fmt.Errorf("nil collection spec")
	}
	m, ok := spec.Maps["alive_block_rate_map"]
	if !ok || m == nil {
		return fmt.Errorf("missing map spec %q", "alive_block_rate_map")
	}
	want := eventRateMapKeyMax + 1
	if m.MaxEntries != want {
		return fmt.Errorf("alive_block_rate_map capacity %d diverges from the userspace-owned reserved event rate key %d (+1 slot) in EVENT_RATE; the C fallback and Go constants are out of sync", m.MaxEntries, eventRateMapKeyMax)
	}
	m.MaxEntries = want
	return nil
}

func cleanupPinnedConnStateMapFiles(log *logrus.Logger, pinPath string) int {
	if pinPath == "" {
		return 0
	}

	removed := 0
	for _, mapName := range []string{"conn_state_map", "tcp_conn_state_map", "udp_conn_state_map"} {
		path := filepath.Join(pinPath, mapName)
		if err := os.Remove(path); err != nil {
			if !os.IsNotExist(err) && log != nil {
				log.Warnf("Failed to remove stale pinned conn-state map %s: %v", mapName, err)
			}
			continue
		}
		removed++
		if log != nil {
			log.Infof("Removed stale pinned conn-state map %s", mapName)
		}
	}
	return removed
}

func cleanupEphemeralBpfPinDirs(log *logrus.Logger, pinPath string) int {
	if pinPath == "" {
		return 0
	}
	entries, err := os.ReadDir(pinPath)
	if err != nil {
		if !os.IsNotExist(err) && log != nil {
			log.Warnf("Failed to read BPF pin path %s: %v", pinPath, err)
		}
		return 0
	}

	removed := 0
	for _, entry := range entries {
		if !entry.IsDir() || !strings.HasPrefix(entry.Name(), "reload-") {
			continue
		}
		path := filepath.Join(pinPath, entry.Name())
		if err := os.RemoveAll(path); err != nil {
			if log != nil {
				log.Warnf("Failed to remove stale reload BPF pin directory %s: %v", entry.Name(), err)
			}
			continue
		}
		removed++
		if log != nil {
			log.Infof("Removed stale reload BPF pin directory %s", entry.Name())
		}
	}
	return removed
}

// logRemovedIncompatiblePinnedMap reports the removal of a pinned map whose
// layout the new datapath object rejects. Removal is destructive -- the map
// holds live connection/session or redirect state and the reloaded program
// starts with an empty one -- so this is a warning that names the map, the pin
// path, and the consequence for established flows, not a step notice.
func logRemovedIncompatiblePinnedMap(log *logrus.Logger, mapName, pinPath string) {
	if log == nil {
		return
	}
	log.WithFields(logrus.Fields{
		"map":      mapName,
		"pin_path": filepath.Join(pinPath, mapName),
	}).Warn("Removed incompatible pinned map: the new datapath object requires a different map layout, so the map's contents (connection tracking / redirect state) are lost and established flows fall back to a fresh decision")
}

func fullLoadBpfObjects(
	log *logrus.Logger,
	bpf *bpfObjects,
	opts *loadBpfOptions,
	soMarkFromDae uint32,
) (err error) {
	// incompatibleMapRetries caps how many pinned-map rejections may trigger a
	// reload attempt. Each retry removes one incompatible pinned map, so more
	// than a couple of rounds means removal is failing and retrying the same
	// load would spin forever.
	const incompatibleMapRetries = 3
	retries := 0
retryLoadBpf:
	netnsID, err := GetDaeNetns().NetnsID()
	if err != nil {
		return fmt.Errorf("failed to get netns id: %w", err)
	}

	// bpf_redirect_peer() is only safe under specific conditions:
	// 1. Netkit device with scrub=NONE (preserves skb->mark across netns boundary)
	// 2. A kernel containing the CVE-2025-37959 fix (mainline >= 6.14.7 or
	//    official stable backports 6.1.139/6.6.91/6.12.29); distro backports
	//    can be opted in with DAE_ALLOW_REDIRECT_PEER=1
	// 3. TC ingress direction ONLY (egress must use bpf_redirect())
	//
	// When enabled, provides ~50% throughput improvement by bypassing CPU backlog.
	useRedirectPeer := uint8(0)
	if GetDaeNetns().IsUsingNetkit() && checkNetkitDeviceCanUseRedirectPeer(log, GetDaeNetns().Dae0().Attrs().Name) {
		// Check kernel version for CVE-2025-37959 fix
		kernelVersion, err := internal.KernelVersion()
		switch {
		case err != nil:
			log.Warnf("Failed to get kernel version: %v; bpf_redirect_peer() disabled", err)
		case consts.IsRedirectPeerSafeKernel(kernelVersion):
			useRedirectPeer = 1
			log.Infof("Safely enabled bpf_redirect_peer() (kernel %v, netkit+scrub=NONE)", kernelVersion)
		case os.Getenv("DAE_ALLOW_REDIRECT_PEER") == "1":
			useRedirectPeer = 1
			log.Warnf("Enabling bpf_redirect_peer() via DAE_ALLOW_REDIRECT_PEER on kernel %v; make sure the kernel contains the CVE-2025-37959 backport", kernelVersion)
		default:
			log.Debugf("Kernel %v lacks a known CVE-2025-37959 fix; bpf_redirect_peer() disabled (set DAE_ALLOW_REDIRECT_PEER=1 to override)",
				kernelVersion)
		}
	}

	// Get peer MAC address. Netkit is created in L2 mode so this should be
	// populated, but keep the zero-MAC fallback for older or unusual kernels.
	peerMac := [6]byte{}
	hwAddr := GetDaeNetns().Dae0Peer().Attrs().HardwareAddr
	if len(hwAddr) == 6 {
		peerMac = [6]byte(hwAddr)
	}

	hasBpfGetCurrentTask := uint8(0)
	if err := features.HaveProgramHelper(ebpf.CGroupSockAddr, asm.FnGetCurrentTask); err == nil {
		hasBpfGetCurrentTask = 1
		log.Debugf("bpf_get_current_task is supported")
	} else {
		log.Warnf("Kernel does not support bpf_get_current_task helper: %v; process names may be truncated or less accurate (degraded to bpf_get_current_comm)", err)
	}

	constants := map[string]any{
		"PARAM": struct {
			tproxyPort           uint32
			controlPlanePid      uint32
			dae0Ifindex          uint32
			daeNetnsId           uint32
			dae0peerMac          [6]byte
			paddingAfterMac      [2]uint8
			useRedirectPeer      uint8
			hasBpfGetCurrentTask uint8
			datapathGeneration   uint16
			daeSocketMark        uint32
		}{
			tproxyPort:           opts.BigEndianTproxyPort,
			controlPlanePid:      uint32(os.Getpid()),
			dae0Ifindex:          uint32(GetDaeNetns().Dae0().Attrs().Index),
			daeNetnsId:           uint32(netnsID),
			dae0peerMac:          peerMac,
			paddingAfterMac:      [2]uint8{0, 0},
			useRedirectPeer:      useRedirectPeer,
			hasBpfGetCurrentTask: hasBpfGetCurrentTask,
			datapathGeneration:   opts.DatapathGeneration,
			daeSocketMark:        soMarkFromDae,
		},
		"EVENT_RATE": eventRateValue(),
	}
	var dataplane bpfDataplane
	if err = loadBpfObjectsWithConstantsAndCustomizer(
		&dataplane,
		opts.CollectionOptions,
		constants,
		func(spec *ebpf.CollectionSpec) error {
			if err := customizeBpfMapSpecs(spec, opts.ConnStateMapMaxEntries, opts.RedirectTrackMapMaxEntries); err != nil {
				return err
			}
			return tuneEventRateMap(spec)
		},
	); err != nil {
		if errors.Is(err, ebpf.ErrMapIncompatible) {
			// Map property is incompatible. Remove the old map and try again.
			prefix := "use pinned map "
			_, after, ok := strings.Cut(err.Error(), prefix)
			if !ok {
				return fmt.Errorf("loading objects: bad format: %w", err)
			}
			mapName, _, _ := strings.Cut(after, ":")
			if retries >= incompatibleMapRetries {
				return fmt.Errorf("loading objects: incompatible pinned map %q persisted after %d removal attempts: %w", mapName, retries, err)
			}
			// A failed removal makes the next load fail identically; surface
			// it instead of spinning on the same error forever.
			if rmErr := os.Remove(filepath.Join(opts.PinPath, mapName)); rmErr != nil && !errors.Is(rmErr, os.ErrNotExist) {
				return fmt.Errorf("remove incompatible pinned map %q: %w", mapName, rmErr)
			}
			retries++
			logRemovedIncompatiblePinnedMap(log, mapName, opts.PinPath)
			goto retryLoadBpf
		}
		// Get detailed log from ebpf.internal.(*VerifierError)
		if log.Level == logrus.FatalLevel {
			if v := reflect.Indirect(reflect.ValueOf(errors.Unwrap(errors.Unwrap(err)))); v.Kind() == reflect.Struct {
				if _log := v.FieldByName("Log"); _log.IsValid() {
					if strSlice, ok := _log.Interface().([]string); ok {
						log.Fatalln(strings.Join(strSlice, "\n"))
					}
				}
			}
		}
		// Use daerrors.WrapBPFError to add helpful context to BPF errors.
		// This replaces string matching with structured error handling.
		err = daerrors.WrapBPFError(err)
		return err
	}
	// Move the always-on datapath objects into the canonical bpfObjects so the
	// rest of the control plane (which references bpf.Tproxy* / bpf.*Map) sees
	// them exactly as before. bpfObjects embeds the generated bpfPrograms and
	// bpfMaps; the offload-free dataplane struct is a superset-less copy so we
	// copy field-by-field.
	assignDataplaneToBpf(bpf, &dataplane)
	// Load the opt-in TCP relay offload programs and maps in a separate,
	// fault-tolerant pass: a kernel that cannot load one of them (e.g. the
	// fentry/skb_send_sock hook on a trimmed router build) must not take down the
	// whole datapath. On failure the corresponding field stays nil and the
	// attach-time gate in setupTCPRelayOffload skips the feature. Only attempt the
	// load when the feature is enabled — otherwise there is nothing to load.
	if tcpRelayOffloadEnabled() {
		if err = loadOffloadBpfObjects(bpf); err != nil {
			log.Debugf("TCP relay offload programs unavailable; offload disabled: %v", err)
		}
	}

	// Initialize the runtime-updatable dae0 ifindex map.
	// PARAM.dae0_ifindex (rodata) is frozen at load time; this ARRAY map
	// allows userspace to hot-update the ifindex if the kernel recreates dae0.
	if bpf.DaeIfindexMap != nil {
		ifidx := uint32(GetDaeNetns().Dae0().Attrs().Index)
		if err = bpf.DaeIfindexMap.Update(uint32(0), ifidx, ebpf.UpdateAny); err != nil {
			return fmt.Errorf("init dae_ifindex_map: %w", err)
		}
	}
	return nil
}

// assignDataplaneToBpf copies the always-on datapath objects loaded into
// *bpfDataplane into the canonical *bpfObjects. bpfObjects embeds the generated
// bpfPrograms/bpfMaps, so the offload-free fields select directly (Go promotes
// embedded-struct fields); the offload fields of bpfObjects are left nil since
// bpfDataplane never binds them.
func assignDataplaneToBpf(bpf *bpfObjects, dp *bpfDataplane) {
	if bpf == nil || dp == nil {
		return
	}
	bpf.TproxyDae0Ingress = dp.TproxyDae0Ingress
	bpf.TproxyDae0peerIngress = dp.TproxyDae0peerIngress
	bpf.TproxyLanEgressL2 = dp.TproxyLanEgressL2
	bpf.TproxyLanEgressL3 = dp.TproxyLanEgressL3
	bpf.TproxyLanIngressL2 = dp.TproxyLanIngressL2
	bpf.TproxyLanIngressL3 = dp.TproxyLanIngressL3
	bpf.TproxyLanWanEgressL2 = dp.TproxyLanWanEgressL2
	bpf.TproxyLanWanEgressL3 = dp.TproxyLanWanEgressL3
	bpf.TproxyWanCgConnect4 = dp.TproxyWanCgConnect4
	bpf.TproxyWanCgConnect6 = dp.TproxyWanCgConnect6
	bpf.TproxyWanCgSendmsg4 = dp.TproxyWanCgSendmsg4
	bpf.TproxyWanCgSendmsg6 = dp.TproxyWanCgSendmsg6
	bpf.TproxyWanCgSockCreate = dp.TproxyWanCgSockCreate
	bpf.TproxyWanCgSockRelease = dp.TproxyWanCgSockRelease
	bpf.TproxyWanEgressL2 = dp.TproxyWanEgressL2
	bpf.TproxyWanEgressL3 = dp.TproxyWanEgressL3
	bpf.TproxyWanIngressL2 = dp.TproxyWanIngressL2
	bpf.TproxyWanIngressL3 = dp.TproxyWanIngressL3
	bpf.TproxyWanLanIngressL2 = dp.TproxyWanLanIngressL2
	bpf.TproxyWanLanIngressL3 = dp.TproxyWanLanIngressL3

	bpf.ActiveRoutingEpochMap = dp.ActiveRoutingEpochMap
	bpf.AliveBlockRateMap = dp.AliveBlockRateMap
	bpf.BpfStatsMap = dp.BpfStatsMap
	bpf.ConnStateMap = dp.ConnStateMap
	bpf.ConntrackArgsMap = dp.ConntrackArgsMap
	bpf.CookiePidMap = dp.CookiePidMap
	bpf.DaeIfindexMap = dp.DaeIfindexMap
	bpf.DomainRoutingMap = dp.DomainRoutingMap
	bpf.EventRingbuf = dp.EventRingbuf
	bpf.ListenSocketMap = dp.ListenSocketMap
	bpf.LpmArrayMap = dp.LpmArrayMap
	bpf.OutboundConnectivityMap = dp.OutboundConnectivityMap
	bpf.ParseCtxScratchMap = dp.ParseCtxScratchMap
	bpf.PktScratchMap = dp.PktScratchMap
	bpf.RedirectTrack = dp.RedirectTrack
	bpf.RouteCtxScratchMap = dp.RouteCtxScratchMap
	bpf.RoutingHandoffMap = dp.RoutingHandoffMap
	bpf.RoutingMap = dp.RoutingMap
	bpf.RoutingMetaMap = dp.RoutingMetaMap
	bpf.UnusedLpmType = dp.UnusedLpmType
	bpf.WanEgressRouteScratchMap = dp.WanEgressRouteScratchMap

	bpf.PARAM = dp.PARAM
}

// loadOffloadBpfObjects loads the opt-in TCP relay offload programs and maps in a
// fault-tolerant pass. Unlike the mandatory datapath load, a failure to load any
// offload object does not abort the whole datapath: the offload feature silently
// stays disabled (the attach-time gate in setupTCPRelayOffload nil-checks these
// fields). This lets a trimmed kernel that cannot load, say, the
// fentry/skb_send_sock accounting hook, still run the always-on tproxy datapath.
//
// The offload programs only reference the offload maps (fast_sock,
// tcp_offload_pause, tcp_offload_sent) and not the PARAM rodata or the main
// datapath maps, so they can be loaded from a self-contained sub-spec. We load
// the eligible sub-spec as one collection: architecture-specific kprobe
// fallbacks are omitted when their pt_regs ABI does not match. If any remaining
// offload program is rejected, the collection fails and we leave every offload
// field nil (feature off) rather than
// leaving a half-loaded, dangling state. The returned collection's maps/programs
// are handed to bpfObjects, which owns their Close() via _BpfClose.
func loadOffloadBpfObjects(bpf *bpfObjects) error {
	// The offload objects were not bound by the mandatory LoadAndAssign pass
	// (bpfDataplane has no offload fields), so load them separately.
	spec, err := loadBpf()
	if err != nil {
		return fmt.Errorf("load spec for offload: %w", err)
	}

	sub := &ebpf.CollectionSpec{
		Programs: make(map[string]*ebpf.ProgramSpec),
		Maps:     make(map[string]*ebpf.MapSpec),
	}
	offloadPrograms := tcpRelayOffloadProgramsForArch(runtime.GOARCH)
	for _, name := range offloadPrograms {
		if ps := spec.Programs[name]; ps != nil {
			sub.Programs[name] = ps
		}
	}
	for _, name := range tcpRelayOffloadMaps {
		if ms := spec.Maps[name]; ms != nil {
			sub.Maps[name] = ms
		}
	}
	if len(sub.Programs) != len(offloadPrograms) || len(sub.Maps) != len(tcpRelayOffloadMaps) {
		return fmt.Errorf("offload spec incomplete: programs %d/%d maps %d/%d",
			len(sub.Programs), len(offloadPrograms), len(sub.Maps), len(tcpRelayOffloadMaps))
	}

	coll, err := ebpf.NewCollection(sub)
	if err != nil {
		return fmt.Errorf("load offload collection: %w", err)
	}

	// Take ownership of the loaded objects; the caller (bpfObjects) closes them.
	if p := coll.Programs["tcp_offload_redirect"]; p != nil {
		bpf.TcpOffloadRedirect = p
	}
	if p := coll.Programs["tcp_offload_sent_account"]; p != nil {
		bpf.TcpOffloadSentAccount = p
	}
	if p := coll.Programs["tcp_offload_sent_account_kprobe"]; p != nil {
		bpf.TcpOffloadSentAccountKprobe = p
	}
	if m := coll.Maps["fast_sock"]; m != nil {
		bpf.FastSock = m
	}
	if m := coll.Maps["tcp_offload_pause"]; m != nil {
		bpf.TcpOffloadPause = m
	}
	if m := coll.Maps["tcp_offload_sent"]; m != nil {
		bpf.TcpOffloadSent = m
	}
	return nil
}
