/* Code generated by go run ../../scripts/gen_ebpf_sync.go; DO NOT EDIT. */

#ifndef DAE_EBPF_SYNC_DEFS_H
#define DAE_EBPF_SYNC_DEFS_H

#define OUTBOUND_DIRECT 0x0
#define OUTBOUND_BLOCK 0x1
#define OUTBOUND_MUST_RULES 0xFC
#define OUTBOUND_CONTROL_PLANE_ROUTING 0xFD
#define OUTBOUND_LOGICAL_OR 0xFE
#define OUTBOUND_LOGICAL_AND 0xFF
#define OUTBOUND_LOGICAL_MASK 0xFE

enum __attribute__((packed)) MatchType {
	MatchType_DomainSet = 0,
	MatchType_IpSet = 1,
	MatchType_SourceIpSet = 2,
	MatchType_Port = 3,
	MatchType_SourcePort = 4,
	MatchType_L4Proto = 5,
	MatchType_IpVersion = 6,
	MatchType_Mac = 7,
	MatchType_ProcessName = 8,
	MatchType_Dscp = 9,
	MatchType_Fallback = 10,
	MatchType_MustRules = 11,
	MatchType_Upstream = 12,
	MatchType_QType = 13,
};

enum L4ProtoType {
	L4ProtoType_TCP = 1,
	L4ProtoType_UDP = 2,
	L4ProtoType_X = 3,
};

enum IpVersionType {
	IpVersionType_4 = 1,
	IpVersionType_6 = 2,
	IpVersionType_X = 3,
};

#endif
