name: BPF Test

on:
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/bpf-test.yml"

permissions: read-all

jobs:
  bpf_tests:
    name: BPF Unit Test
    runs-on: ubuntu-latest
    continue-on-error: true
    strategy:
      matrix:
        env:
        - VERSION: 15
        - VERSION: 16
        - VERSION: 17
        - VERSION: 18
        - VERSION: 19

    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 0

      - name: Install Dependencies
        env: ${{ matrix.env }}
        run: |
          sudo apt-get update -y
          sudo apt-get install -y clang-$VERSION llvm-$VERSION

      - name: Run BPF tests
        env: ${{ matrix.env }}
        run: |
          git submodule update --init
          sudo CLANG=clang-$VERSION make ebpf-test || (echo "Run 'make ebpf-test' locally to investigate failures"; exit 1)

