name: BPF Test

on:
  pull_request:
    paths:
      - "**/*.c"
      - "**/*.h"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/bpf-test.yml"

permissions: read-all

jobs:
  bpf_tests:
    name: BPF Unit Test
    runs-on: ubuntu-24.04
    steps:
      - name: Checkout code
        uses: actions/checkout@d632683dd7b4114ad314bca15554477dd762a938 # v4.2.0
        with:
          persist-credentials: false
          fetch-depth: 0
      - name: Run BPF tests
        run: |
          git submodule update --init
          sudo make ebpf-test || (echo "Run 'make ebpf-test' locally to investigate failures"; exit 1)

