name: Go Test

on:
  pull_request:
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-test.yml"
      - "Makefile"
  push:
    branches:
      - main
    paths:
      - "**/*.go"
      - "go.mod"
      - "go.sum"
      - ".github/workflows/go-test.yml"
      - "Makefile"

permissions: read-all

jobs:
  go_test:
    name: Go Unit Test
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Go 1.26
        run: |
          wget -q https://go.dev/dl/go1.26.0.linux-amd64.tar.gz
          sudo rm -rf /usr/local/go
          sudo tar -C /usr/local -xzf go1.26.0.linux-amd64.tar.gz
          echo "/usr/local/go/bin" >> $GITHUB_PATH
          echo "GOPATH=$(go env GOPATH)" >> $GITHUB_ENV

      - name: Go cache
        uses: actions/cache@v4
        with:
          path: |
            ~/.cache/go-build
            ~/go/pkg/mod
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            ${{ runner.os }}-go-

      - name: Run tests
        run: |
          git submodule update --init --recursive
          go test -tags dae_stub_ebpf ./...
