#      _
#   __| | __ _  ___
#  / _` |/ _` |/ _ \
# | (_| | (_| |  __/
#  \__,_|\__,_|\___|
#
# Copyright (C) 2023 @daeuniverse <https://github.com/daeuniverse>
#
# This is a open-source software, liscensed under the AGPL-3.0 License.
# See /License for more information.

name: Publish Pre-release
run-name: Publish prerelease ${{ inputs.tag }} by @${{ github.actor }}

on:
  workflow_dispatch:
    inputs:
      tag:
        type: string
        required: true

jobs:
  pre-actions:
    uses: daeuniverse/ci-seed-jobs/.github/workflows/pre-actions.yml@master
    with:
      repository: ${{ github.repository }}
      ref: ${{ github.sha }}
      fetch-depth: 0
    secrets: inherit

  build:
    uses: daeuniverse/dae/.github/workflows/seed-release-build.yml@main
    with:
      tag: ${{ inputs.tag }}

  upload-release:
    needs: [build]
    uses: daeuniverse/dae/.github/workflows/seed-release-build.yml@main
    with:
      prerelease: true
